export { default as HomePage } from './HomePage';
export { default as PokemonGenerationsPage } from './PokemonGenerationsPage';
export { default as KantoPage } from './KantoPage';
export { default as JohtoPage } from './JohtoPage';
// export { default as HoennPage } from './HoennPage';
// export { default as SinnohPage } from './SinnohPage';
// export { default as UnovaPage } from './UnovaPage';
// export { default as KalosPage } from './KalosPage';
// export { default as AlolaPage } from './AlolaPage';
// export { default as GalarPage } from './GalarPage';
// export { default as PaldeaPage } from './PaldeaPage';
export { default as PokemonPage } from './PokemonPage';
export { default as SearchPokemonPage } from './SearchPokemonPage';
export { default as NotFoundPage } from './NotFoundPage';